### ISSUE TITLE
drop BUILDDIR from config.opts?

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/config.opts#1]
Since we have a lot of super repositories by now I would like to have the different config.opts that are in use in a separate repo (this one). At the moment I copied all relevant CXX_FLAGS from dune-stuff, so that a build with cmake and autotools should really use the same build flags in the end. This process could surely be automated for the other compilers at some point. This also ensures that `-f` options are the same between release and debug builds which allows for a debug situation where the core modules and external libraries are release builts and the relevant dune module is a debug build. This requires, however, that the `BUILDDIR` define is removed from the config.opts file since we specify different build dirs for different builds (of course we do^^).

In addition I would like to use these config.opts for autotools as well as cmake builds and it is clear that autotools can not cope with a `BUILDDIR`. So there are one or two good reasons (IMHO) do drop the `BUILDDIR` define from the config.opts files (if we wish to share the config.opts between super modules).

What do you think, @renemilk ? We would then have to define it in our build or startup scripts, which would be fine for me. What about the buildbot? If no one else feels like sharing the config.opts I would just remove the define and use this repo only in our old supermodules where we did not switch to cmake yet (yes, those still exist).

**Comment by renefritze** [comment]
I'm happy with the where configs were before this module. Changing/adding a flag across super modules is very rare. I don't get why you would purposefully want to mix debug and release builds across dune modules. Autotools can handle out-of-source/shadow building just fine, it is not at all clear that they cannot. If you know of a problem, then that's a module/DUNE specific problem and we should fix that (own modules) or report it.

**Comment by renefritze** [comment]
Is this still an issue @ftalbrecht ? Does the bash evalution stuff I do in the `stinson/` subdir (for example) help?

**Comment by ftalbrecht** [comment]
I think we an close this...
